quarkus.datasource.db-kind=${DB_KIND}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_JDBC_URL}
quarkus.datasource.jdbc.additional-jdbc-properties.sslmode=${DB_SSL_MODE}
quarkus.datasource.jdbc.additional-jdbc-properties.channelBinding=${DB_CHANNEL_BINDING}

# Configurações do servidor HTTP
quarkus.http.host=0.0.0.0

# CORS Configuration

# Habilitar o filtro CORS
quarkus.http.cors.enabled=true

# Origens permitidas (separadas por vírgula)
quarkus.http.cors.origins=${CORS_ORIGINS}

# Métodos HTTP permitidos
quarkus.http.cors.methods=GET,POST,PUT,DELETE

# Headers permitidos
quarkus.http.cors.headers=Content-Type,Authorization

# Tempo de cache para preflight (opcional)
quarkus.http.cors.access-control-max-age=24H

# Permitir credenciais (cookies)
quarkus.http.cors.access-control-allow-credentials=true